AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
# Description: An AWS Serverless Specification template describing your function.
Resources:
  lambda:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: main.lambda_handler
      Runtime: python3.8
      # Description: ''
      # MemorySize: 128
      # Timeout: 20
      CodeUri: ./src/
      # Policies:
      #   - S3CrudPolicy:
      #       BucketName: qiita-data
