services:
  database:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: Asia/Tokyo
    volumes:
      - ./conf/my.cnf:/etc/mysql/conf.d/my.cnf

  flyway:
    image: flyway/flyway:10-alpine
    command: -url=jdbc:mysql://database:3306/${MYSQL_DATABASE} -user=root -password=${MYSQL_ROOT_PASSWORD} -cleanDisabled=false ${FLYWAY_COMMAND:-}
    volumes:
      - ./sql:/flyway/sql
