jenkins:
  agentProtocols:
  - "JNLP4-connect"
  - "Ping"
  authorizationStrategy:
    roleBased:
      roles:
        global:
        - entries:
          - user: "admin"
          - user: "tagjmp@gmail.com"
          name: "admin"
          pattern: ".*"
          permissions:
          - "Overall/Administer"
        - entries:
          - user: "user"
          name: "job-runner"
          pattern: ".*"
          permissions:
          - "Job/Cancel"
          - "Overall/Read"
          - "Job/Build"
          - "Run/Update"
          - "View/Create"
          - "View/Delete"
          - "Job/Read"
          - "View/Read"
          - "View/Configure"
          - "Run/Replay"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  labelAtoms:
  - name: "built-in"
  markupFormatter: "plainText"
  mode: NORMAL
  myViewsTabBar: "standard"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  # remotingSecurity:
    # enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    googleOAuth2:
      clientId: "${GOOGLE_OAUTH2_CLIENT_ID}"
      clientSecret: "${GOOGLE_OAUTH2_CLIENT_SECRET}"
    # local:
    #   allowsSignup: false
    #   enableCaptcha: false
    #   users:
    #   - id: "admin"
    #     name: "admin"
    #     password: "admin"
    #     properties:
    #     - "myView"
    #     - preferredProvider:
    #         providerId: "default"
    #     - "slack"
    #     - "timezone"
    #     - "experimentalFlags"
    #     - mailer:
    #         emailAddress: "a@b.c"
    #     - "apiToken"
    #   - id: "user"
    #     name: "test"
    #     password: "user"
    #     properties:
    #     - "apiToken"
    #     - "myView"
    #     - preferredProvider:
    #         providerId: "default"
    #     - "slack"
    #     - "timezone"
    #     - "experimentalFlags"
    #     - mailer:
    #         emailAddress: "a@b.c"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  simpleTheme:
    elements:
    - cssUrl:
        url: "https://jenkins-themes.alefnode.com/dist/material-${JENKINS_THEME_COLOR}.css"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  # globalJobDslSecurityConfiguration:
    # useScriptSecurity: true
  sSHD:
    port: -1
  scriptApproval:
    approvedScriptHashes:
    - "SHA512:74fc91c592a1026df64c18fa6ee284ff28cfd8226e9ed790ee9cd92da65dc8403e3bea1829f2dde968931c4865ab3c6bc1a8b831d6fb566755a86f8095b136ac"
    - "SHA512:ca92443d2e7b2639a00c7987d095d0f0e6614aac64e75cbc01290b5428048df9751de626bf1dffdaec728112ec4d5c9f0536943eda9a5f2baa13eb5195f25777"
unclassified:
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  junitTestResultStorage:
    storage: "file"
  location:
  #   adminAddress: "まだアドレスが設定されていません。 <nobody@nowhere>"
    url: "${JENKINS_URL}"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  pollSCM:
    pollingThreadCount: 10
  prismConfiguration:
    theme: PRISM
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  slackNotifier:
    botUser: false
    sendAsText: false
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
