name: Build and Push Docker Image

on:
  push:
    branches:
      - 'feature/*'
    paths:
      - 'terragrunt/modules/jenkins/docker-image/**'
  pull_request:
    types: [closed]
    branches:
      - 'feature/*'
    paths:
      - 'terragrunt/modules/jenkins/docker-image/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials for dev
      if: startsWith(github.ref, 'refs/heads/feature/')
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
        aws-region: ap-northeast-1

    - name: Set up secret for dev
      if: startsWith(github.ref, 'refs/heads/feature/')
      run: echo "AWS_ACCOUND_ID=${{ secrets.AWS_ACCOUND_ID_DEV }}" >> $GITHUB_ENV

    - name: Build and push Docker image2
      run: |
        cd terragrunt/modules/jenkins/docker-image/
        make
        make push
