name: Build and Push Docker Image

on:
  push:
    # branches:
    #   - 'feature/*'
    # paths:
      # - 'terragrunt/modules/jenkins/docker-image/**'
  pull_request:
    types: [closed]
    # branches:
    #   - 'feature/*'
    # paths:
      # - 'terragrunt/modules/jenkins/docker-image/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{
      (github.ref == 'refs/heads/main' && 'production') ||
      (github.ref == 'refs/heads/staging' && 'staging') || 'development' }}
    steps:
    - name: test
      run: echo "${{ github.ref }}"

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        working-dir: terragrunt/modules/
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Set up AWS credentials for dev
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Set up secret for dev
      run: echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV

    - name: Build and push Docker image2
      run: |
        cd terragrunt/modules/jenkins/docker-image/
        make
        make push
