name: Build and Push Docker Image

on:
  push:
    paths:
      - 'terragrunt/modules/jenkins/docker-image/**'

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{
      (github.ref == 'refs/heads/main' && 'production') ||
      (github.ref == 'refs/heads/staging' && 'staging') || 'development' }}
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Set up secret
      run: echo "AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}" >> $GITHUB_ENV

    - name: Build and push Docker image2
      run: |
        cd terragrunt/modules/jenkins/docker-image/
        make
        make push
