name: Build and Push Docker Image

on:
  push:
    branches:
      - 'feature/*'
    # paths:
      # - 'terragrunt/modules/jenkins/docker-image/**'
  pull_request:
    types: [closed]
    branches:
      - 'feature/*'
    # paths:
      # - 'terragrunt/modules/jenkins/docker-image/**'

jobs:
  build:
    runs-on: ubuntu-latest
    # environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}
    environment: development
    steps:
    - name: Show env
      run: echo "env=${{ job.envrionment }}"

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS credentials for dev
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-1

    - name: Set up secret for dev
      run: echo "AWS_ACCOUND_ID=${{ secrets.AWS_ACCOUND_ID }}" >> $GITHUB_ENV

    - name: Build and push Docker image2
      run: |
        cd terragrunt/modules/jenkins/docker-image/
        make
        make push
