name: Check Pull Requests

on:
  pull_request:
    branches:
      - main
      - staging
  push:
    branches:
      - feature/*

jobs:
  terraform:
    name: Lint and Plan Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write
      pull-requests: write
    environment: development
    env:
      ENV: |-
        ${{
          github.base_ref == 'main' && 'prd'
          || github.base_ref == 'staging' && 'stg'
          || 'dev'
        }}
      TF_IN_AUTOMATION: true
    steps:
      # Setup
      - uses: hashicorp/setup-terraform@v3
      - uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
      - uses: terraform-linters/setup-tflint@v4
      - uses: shmokmt/actions-setup-tfcmt@v2

      # Checkout
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      # Configure AWS Credential
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::384081048358:role/ReadOnlyOidc-${{ env.ENV }}
          aws-region: ap-northeast-1

      # Execute Terraform fmt
      - name: Terraform Format
        id: fmt
        uses: gh640/command-result-action@v1
        with:
          command: terraform fmt -check -recursive -diff
          cwd: terragrunt/modules/
        continue-on-error: true

      # Execute Terraform validate
      - name: Terraform validate
        id: validate
        uses: gh640/command-result-action@v1
        with:
          command: terragrunt run-all validate --terragrunt-no-color -no-color
          cwd: terragrunt/envs/${{ env.ENV }}/
        continue-on-error: true

      # TFLint
      - name: Init TFLint
        run: tflint --init --config=$(pwd)/.tflint.hcl
        working-directory: terragrunt/
      - name: Run TFLint
        id: tflint
        run: |
          echo "TFLINT_RESULT<<ENND" >> $GITHUB_ENV
          tflint --config=$(pwd)/.tflint.hcl --recursive --format compact 2>&1 >> $GITHUB_ENV || TFLINT_FAILED=1
          echo "ENND" >> $GITHUB_ENV
          echo "TFLINT_FAILED=$TFLINT_FAILED" >> $GITHUB_ENV
        working-directory: terragrunt/
        continue-on-error: true
      - run: |
          for line in "$TFLINT_RESULT"; do echo "$line" | sed "s#^modules/#terragrunt/modules/#g"; done

      # Init Terraform
      # - name: Terraform init
      #   id: init
      #   uses: gh640/command-result-action@v1
      #   with:
      #     command: terragrunt run-all init --terragrunt-no-color -no-color
      #     cwd: terragrunt/envs/${{ env.ENV }}/
      #   continue-on-error: true
      - name: Terragrunt init
        working-directory: terragrunt/
        env:
          # ENV: ${{ vars.ENV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make init
        continue-on-error: true

      # Output Result to PR Comment
      - name: PR comment
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        env:
          TFLINT_FAILED: ${{ env.TFLINT_FAILED }}
          TFLINT_RESULT: ${{ env.TFLINT_RESULT }}
        with:
          header: terraform
          hide_and_recreate: true
          hide_classify: "OUTDATED"
          message: |
            ${{ steps.terraform-docs.outputs.num_changed > 0 && '✅' || '➖' }} terraform docs (number of updated = ${{ steps.terraform-docs.outputs.num_changed }})
            <details>
            <summary>${{ steps.fmt.outputs.exitCode == 0 && '✅' || '❌' }} terraform fmt</summary>

            ```diff
            ${{ steps.fmt.outputs.stderr }}${{ steps.fmt.outputs.stdout }}
            ```

            </details>
            <details>
            <summary>${{ steps.init.outputs.exitCode == 0 && '✅' || '❌' }} terraform init</summary>

            ```
            ${{ steps.init.outputs.stderr }}${{ steps.init.outputs.stdout }}
            ```

            </details>
            <details>
            <summary>${{ steps.validate.outputs.exitCode == 0 && '✅' || '❌' }} terraform validate</summary>

            ```
            ${{ steps.validate.outputs.stderr }}${{ steps.validate.outputs.stdout }}
            ```

            </details>
            <details>
            <summary>${{ env.TFLINT_FAILED != 1 && '✅' || '❌' }} terraform tflint</summary>

            ```
            ${{ env.TFLINT_RESULT }}
            ```

            </details>

      - name: Check Result
        run: exit 1
        env:
          TFLINT_FAILED: ${{ env.TFLINT_FAILED }}
        if: ${{ steps.fmt.outputs.exitCode != 0 || steps.init.outputs.exitCode != 0 || steps.validate.outputs.exitCode != 0 || env.TFLINT_FAILED == 1 }}

      # Create Terraform Docs
      - name: Render terraform docs and push changes back to PR
        id: terraform-docs
        uses: terraform-docs/gh-actions@main
        with:
          find-dir: terragrunt/modules/
          output-file: README.md
          output-method: inject
          git-push: true
          git-commit-message: Update Terraform Docs

      - name: Terragrunt plan
        working-directory: terragrunt/
        env:
          # ENV: ${{ vars.ENV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make plan
