name: Deploy

on:
  push:
    branches:
      - main
      - staging

jobs:
  terraform_apply:
    name: Apply Terraform
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    environment: |-
      ${{
        github.ref == 'refs/heads/main' && 'production'
        || github.ref == 'refs/heads/staging' && 'staging'
        || 'error'
      }}
    env:
      TF_IN_AUTOMATION: true
    steps:
      # Setup
      - uses: hashicorp/setup-terraform@v3
      - uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest
      - uses: kerraform/setup-tfnotify@v1

      # Checkout
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # AWS Credential
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::384081048358:role/AdministratorOidc-${{ vars.ENV }}
          aws-region: ap-northeast-1

      - name: Terragrunt apply
        working-directory: terragrunt/
        env:
          ENV: ${{ vars.ENV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make apply
