name: terraform docs

on:
  pull_request:
    branches:
      - main
    # paths:
    #   - terragrunt/modules/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      TF_IN_AUTOMATION: true
    defaults:
      run:
        working-directory: terragrunt/modules/
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Setup Terragrunt
      uses: autero1/action-terragrunt@v1.1.0
      with:
        terragrunt_version: latest
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Render terraform docs and push changes back to PR
      id: terraform-docs
      uses: terraform-docs/gh-actions@main
      with:
        find-dir: terragrunt/modules/
        output-file: README.md
        output-method: inject
        git-push: true
        git-commit-message: update terraform docs

    - name: Terraform Format
      id: fmt
      uses: gh640/command-result-action@v1
      with:
        command: terraform fmt -check -recursive -diff
        cwd: terragrunt/modules/
      continue-on-error: true

      - name: Terraform init
      id: init
      uses: gh640/command-result-action@v1
      with:
        command: terragrunt init
        cwd: terragrunt/envs/dev/
      continue-on-error: true

      - name: Terraform validate
      id: validate
      uses: gh640/command-result-action@v1
      with:
        command: terragrunt validate
        cwd: terragrunt/envs/dev/
      continue-on-error: true

      - name: Terraform plan
      id: plan
      uses: gh640/command-result-action@v1
      with:
        command: terragrunt plan
        cwd: terragrunt/envs/dev/
      continue-on-error: true

    - name: Add comment to PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: |
          ${{ steps.terraform-docs.outputs.num_changed > 0 && '✅' || '➖' }} terraform fmt (number of updated = ${{ steps.terraform-docs.outputs.num_changed }})
          <details>
          <summary>${{ steps.fmt.outputs.exitCode == 0 && '✅' || '❌' }} terraform fmt</summary>

          ```patch
          ${{ steps.fmt.outputs.stdout }}
          ```

          </details>
          <details>
          <summary>${{ steps.init.outputs.exitCode == 0 && '✅' || '❌' }} terraform init</summary>

          ```
          ${{ steps.init.outputs.stdout }}
          ```

          </details>
          <details>
          <summary>${{ steps.validate.outputs.exitCode == 0 && '✅' || '❌' }} terraform validate</summary>

          ```
          ${{ steps.validate.outputs.stdout }}
          ```

          </details>
          <details>
          <summary>${{ steps.plan.outputs.exitCode == 0 && '✅' || '❌' }} terraform plan</summary>

          ```
          ${{ steps.plan.outputs.stdout }}
          ```

          </details>


    # - name: Terraform Init
    #   id: init
    #   run: terraform init

    # - name: Post Init
    #   # if: always() && github.ref != 'refs/heads/master' && (steps.init.outcome == 'success' || steps.init.outcome == 'failure')
    #   uses: robburger/terraform-pr-commenter@v1
    #   with:
    #     commenter_type: init
    #     commenter_input: ${{ format('{0}{1}', steps.init.outputs.stdout, steps.init.outputs.stderr) }}
    #     commenter_exitcode: ${{ steps.init.outputs.exitcode }}

    # - name: Terraform Validate
    #   id: validate
    #   run: terraform validate

    # - name: Post Validate
    #   # if: always() && github.ref != 'refs/heads/master' && (steps.validate.outcome == 'success' || steps.validate.outcome == 'failure')
    #   uses: robburger/terraform-pr-commenter@v1
    #   with:
    #     commenter_type: validate
    #     commenter_input: ${{ format('{0}{1}', steps.validate.outputs.stdout, steps.validate.outputs.stderr) }}
    #     commenter_exitcode: ${{ steps.validate.outputs.exitcode }}

    # - name: Terraform Plan
    #   id: plan
    #   run: terraform plan -out workspace.plan

    # - name: Post Plan
    #   # if: always() && github.ref != 'refs/heads/master' && (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure')
    #   uses: robburger/terraform-pr-commenter@v1
    #   with:
    #     commenter_type: plan
    #     commenter_input: ${{ format('{0}{1}', steps.plan.outputs.stdout, steps.plan.outputs.stderr) }}
    #     commenter_exitcode: ${{ steps.plan.outputs.exitcode }}
