name: terraform docs

on:
  pull_request:
    branches:
      - main
    paths:
      - terragrunt/modules/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: development
    steps:
    - name: Checkout target branch
      uses: actions/checkout@v3
      with:
        ref: ${{ github.head_ref }}

    - name: Render terraform docs and push changes back to PR
      uses: terraform-docs/gh-actions@main
      with:
        find-dir: terragrunt/modules/
        output-file: README.md
        output-method: inject
        git-push: "true"

    - name: Add comment to PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        message: 'Terraform Docs is updated.'
