name: terraform docs

on:
  push:
    branches:
      - main
      - staging
    # paths:
    #   - terragrunt/modules/**

jobs:
  build:
    runs-on: ubuntu-latest
    environment: |-
      ${{
        github.ref == 'main' && 'production'
        || github.ref == 'staging' && 'staging'
        || 'development'
      }}
    env:
      TF_IN_AUTOMATION: true
    steps:

      # Setup
      - uses: hashicorp/setup-terraform@v3
      - uses: autero1/action-terragrunt@v1.3.2
        with:
          terragrunt_version: latest

      # Checkout
      - name: Checkout target branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      # AWS Credential
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Terragrunt plan
        working-directory: terragrunt/
        env:
          ENV: ${{ vars.ENV }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: make apply
